### ISSUE TITLE
이름이 이상합니다

### ISSUE THREAD

**Issue by AtSignRANK** [R2turnTrue/projecttl-dont-coding-toomany#2]
projecttl-dont-coding-toomany
는 프젝 코딩 너무 많이하면 안돼 인데,
프젝 코딩하면 안돼로 고쳐야합니다.
-toomany 를 삭제해주세요

**Comment by R2turnTrue** [comment]
그러면 프젝섭이 망합니다

**Comment by AtSignRANK** [comment]
It's Okay 괜찮아 맛이라도 봤잖아 다시 현실로 돌아가 그래 취직하고 잘살아 잘 잊혀지고 있잖아
